[package]
name = "catan_service"
version = "0.1.0"
edition = "2018"
[dev-dependencies]
cargo-make = "0.36.11"
serial_test = "2.0.0"
actix-web-test = "0.0.1"

[dependencies]
azure_data_cosmos = "0.13.0"
azure_core = "0.13.0"
tokio = { version = "1.28.2", features = ["full", "test-util"] }
actix-cors = "0.6.4"
actix-rt = "2.2.0"
actix-web = { version = "4.3.1", features = ["openssl"] }
arrayvec = "0.7.1"
once_cell = "1.8.0"
reqwest = { version = "0.11.8", features = ["json"] }
rand = "0.8.4"
serde_json = "1.0.67"
serde = { version = "1.0.123", features = ["derive"] }
env_logger = "0.10.0"
azure_sdk_core = "0.43.7"
futures = "0.3.28"
log = "0.4.19"
tracing = "0.1.37"
actix-web-actors = "4.2.0"
actix = "0.13.0"
openssl = "0.10.55"
anyhow = "1.0.71"
bcrypt = "0.15.0"
jsonwebtoken = "8.3.0"
num-traits = "0.2.15"
actix-service = "2.0.2"
lazy_static = "1.4.0"
strum = "0.25.0"
strum_macros = "0.25.1"
serde_with = "3.0.0"
parking_lot = "0.12.1"
